FROM openjdk:8-jdk-nanoserver
MAINTAINER Christopher Guckes <christopher.guckes@torq-dev.de>

WORKDIR /
RUN md fitnesse
RUN md fitnesse/src
RUN md fitnesse-initial

ADD . /fitnesse
ADD ./src/main/resources /fitnesse-initial

WORKDIR fitnesse

RUN ./mvnw.cmd clean install

VOLUME c:/fitnesse/src/main/resources
VOLUME c:/fitnesse/src/test/java
ENTRYPOINT ["/fitnesse/start.bat"]